version: '3.10'

services:
  db_collector:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_collector:/var/lib/postgresql/data
    env_file:
      - ./.env

  collector:
    build: .
    restart: always
    depends_on:
      - db_collector
    env_file:
      - ./.env


volumes:
  db_collector: